#!/bin/sh

sudo chmod 666 /tmp/slow.log
sudo chmod 666 /tmp/access.log

hms=`date +"%H%M%S"`
mkdir /tmp/profiles/$hms
pt-query-digest /tmp/slow.log > /tmp/profiles/$hms/mysql_log.txt
cat /tmp/access.log | kataribe > /tmp/profiles/$hms/nginx_log.txt
echo '' > /tmp/slow.log
echo '' > /tmp/access.log
